// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.12.0 (commit 4fdb8d923f39ed592931ad4c7e6391ed99b9fe3a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import AiWriteRecommendationReducer from "./ai_write_recommendation_reducer";
export { AiWriteRecommendationReducer };
import ApproveUnlockReducer from "./approve_unlock_reducer";
export { ApproveUnlockReducer };
import ConfirmUnlockStatusReducer from "./confirm_unlock_status_reducer";
export { ConfirmUnlockStatusReducer };
import ConnectSmartcarVehicleReducer from "./connect_smartcar_vehicle_reducer";
export { ConnectSmartcarVehicleReducer };
import GenerateCloseoutReducer from "./generate_closeout_reducer";
export { GenerateCloseoutReducer };
import IdentityConnectedReducer from "./identity_connected_reducer";
export { IdentityConnectedReducer };
import IdentityDisconnectedReducer from "./identity_disconnected_reducer";
export { IdentityDisconnectedReducer };
import IngestSmartcarSnapshotReducer from "./ingest_smartcar_snapshot_reducer";
export { IngestSmartcarSnapshotReducer };
import PushTelemetryReducer from "./push_telemetry_reducer";
export { PushTelemetryReducer };
import RecordUnlockCommandReducer from "./record_unlock_command_reducer";
export { RecordUnlockCommandReducer };
import ReserveVehicleReducer from "./reserve_vehicle_reducer";
export { ReserveVehicleReducer };
import SeedDemoDataReducer from "./seed_demo_data_reducer";
export { SeedDemoDataReducer };
import StartReturnReducer from "./start_return_reducer";
export { StartReturnReducer };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import AiRecommendationsRow from "./ai_recommendations_table";
export { AiRecommendationsRow };
import CommunityRow from "./community_table";
export { CommunityRow };
import ResidentsRow from "./residents_table";
export { ResidentsRow };
import TelemetryRow from "./telemetry_table";
export { TelemetryRow };
import TripEventsRow from "./trip_events_table";
export { TripEventsRow };
import TripsRow from "./trips_table";
export { TripsRow };
import VehicleSnapshotsRow from "./vehicle_snapshots_table";
export { VehicleSnapshotsRow };
import VehiclesRow from "./vehicles_table";
export { VehiclesRow };

// Import and reexport all types
import AiRecommendation from "./ai_recommendation_type";
export { AiRecommendation };
import Community from "./community_type";
export { Community };
import Resident from "./resident_type";
export { Resident };
import Telemetry from "./telemetry_type";
export { Telemetry };
import Trip from "./trip_type";
export { Trip };
import TripEvent from "./trip_event_type";
export { TripEvent };
import Vehicle from "./vehicle_type";
export { Vehicle };
import VehicleSnapshot from "./vehicle_snapshot_type";
export { VehicleSnapshot };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'ai_recommendations',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'ai_recommendations_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AiRecommendationsRow),
  __table({
    name: 'community',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'community_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CommunityRow),
  __table({
    name: 'residents',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'residents_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ResidentsRow),
  __table({
    name: 'telemetry',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'telemetry_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TelemetryRow),
  __table({
    name: 'trip_events',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'trip_events_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TripEventsRow),
  __table({
    name: 'trips',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'trips_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TripsRow),
  __table({
    name: 'vehicle_snapshots',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'vehicle_snapshots_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VehicleSnapshotsRow),
  __table({
    name: 'vehicles',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'vehicles_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, VehiclesRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("ai_write_recommendation", AiWriteRecommendationReducer),
  __reducerSchema("approve_unlock", ApproveUnlockReducer),
  __reducerSchema("confirm_unlock_status", ConfirmUnlockStatusReducer),
  __reducerSchema("connect_smartcar_vehicle", ConnectSmartcarVehicleReducer),
  __reducerSchema("generate_closeout", GenerateCloseoutReducer),
  __reducerSchema("ingest_smartcar_snapshot", IngestSmartcarSnapshotReducer),
  __reducerSchema("push_telemetry", PushTelemetryReducer),
  __reducerSchema("record_unlock_command", RecordUnlockCommandReducer),
  __reducerSchema("reserve_vehicle", ReserveVehicleReducer),
  __reducerSchema("seed_demo_data", SeedDemoDataReducer),
  __reducerSchema("start_return", StartReturnReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.12.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** A typed query builder for this remote SpacetimeDB module. */
export const query: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

