// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  vehicleId: __t.u64(),
  tripId: __t.u64(),
  source: __t.string(),
  batteryPct: __t.i32(),
  odometer: __t.f64(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  locationConfirmed: __t.bool(),
  lockStatus: __t.string(),
  chargeStatus: __t.string(),
  smartcarVehicleId: __t.string(),
};
