// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  tripId: __t.u64().name("trip_id"),
  battery: __t.i32(),
  odometerDelta: __t.f32().name("odometer_delta"),
  harshBrake: __t.bool().name("harsh_brake"),
  geofenceOk: __t.bool().name("geofence_ok"),
  timestamp: __t.timestamp(),
  source: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  locationConfirmed: __t.bool().name("location_confirmed"),
  lockStatus: __t.string().name("lock_status"),
});
