// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Telemetry", {
  id: __t.u64(),
  tripId: __t.u64(),
  battery: __t.i32(),
  odometerDelta: __t.f32(),
  harshBrake: __t.bool(),
  geofenceOk: __t.bool(),
  timestamp: __t.timestamp(),
  source: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  locationConfirmed: __t.bool(),
  lockStatus: __t.string(),
});


