// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("Vehicle", {
  id: __t.u64(),
  model: __t.string(),
  battery: __t.i32(),
  location: __t.string(),
  status: __t.string(),
  source: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  locationConfirmed: __t.bool(),
  lockStatus: __t.string(),
  chargeStatus: __t.string(),
  smartcarVehicleId: __t.string(),
});


