// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  vehicleId: __t.u64().name("vehicle_id"),
  tripId: __t.u64().name("trip_id"),
  source: __t.string(),
  batteryPct: __t.i32().name("battery_pct"),
  odometer: __t.f64(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  locationConfirmed: __t.bool().name("location_confirmed"),
  lockStatus: __t.string().name("lock_status"),
  chargeStatus: __t.string().name("charge_status"),
  smartcarVehicleId: __t.string().name("smartcar_vehicle_id"),
  capturedAt: __t.timestamp().name("captured_at"),
});
